// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_keys (name, organization_id)
VALUES ($1, $2)
RETURNING id, name, organization_id, key_hash, created_at
`

type CreateApiKeyParams struct {
	Name           string      `json:"name"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey, arg.Name, arg.OrganizationID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.KeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT id, name, organization_id, key_hash, created_at FROM api_keys WHERE id = $1
`

func (q *Queries) GetApiKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.KeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const getOrgFromApiKey = `-- name: GetOrgFromApiKey :one
SELECT organizations.id, organizations.name, organizations.created_at, organizations.updated_at FROM api_keys 
JOIN organizations on api_keys.organization_id = organizations.id
WHERE api_keys.key_hash = $1
LIMIT 1
`

func (q *Queries) GetOrgFromApiKey(ctx context.Context, keyHash string) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrgFromApiKey, keyHash)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, name, organization_id, key_hash, created_at FROM api_keys ORDER BY created_at DESC LIMIT $1
`

func (q *Queries) ListApiKeys(ctx context.Context, limit int32) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeys, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OrganizationID,
			&i.KeyHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
