// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: buckets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createS3Bucket = `-- name: CreateS3Bucket :one
INSERT INTO s3_buckets (name, organization_id)
VALUES ($1, $2)
RETURNING id, name, organization_id, created_at
`

type CreateS3BucketParams struct {
	Name           string      `json:"name"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) CreateS3Bucket(ctx context.Context, arg CreateS3BucketParams) (S3Bucket, error) {
	row := q.db.QueryRow(ctx, createS3Bucket, arg.Name, arg.OrganizationID)
	var i S3Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteS3BucketById = `-- name: DeleteS3BucketById :one
DELETE FROM s3_buckets
WHERE id = $1
RETURNING id, name, organization_id, created_at
`

func (q *Queries) DeleteS3BucketById(ctx context.Context, id pgtype.UUID) (S3Bucket, error) {
	row := q.db.QueryRow(ctx, deleteS3BucketById, id)
	var i S3Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteS3BucketByName = `-- name: DeleteS3BucketByName :one
DELETE FROM s3_buckets
WHERE name = $1
  AND organization_id = $2
RETURNING id, name, organization_id, created_at
`

type DeleteS3BucketByNameParams struct {
	Name           string      `json:"name"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

func (q *Queries) DeleteS3BucketByName(ctx context.Context, arg DeleteS3BucketByNameParams) (S3Bucket, error) {
	row := q.db.QueryRow(ctx, deleteS3BucketByName, arg.Name, arg.OrganizationID)
	var i S3Bucket
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OrganizationID,
		&i.CreatedAt,
	)
	return i, err
}

const getBucketByName = `-- name: GetBucketByName :one
SELECT FROM s3_buckets 
WHERE name = $1 and organization_id = $2
`

type GetBucketByNameParams struct {
	Name           string      `json:"name"`
	OrganizationID pgtype.UUID `json:"organization_id"`
}

type GetBucketByNameRow struct {
}

func (q *Queries) GetBucketByName(ctx context.Context, arg GetBucketByNameParams) (GetBucketByNameRow, error) {
	row := q.db.QueryRow(ctx, getBucketByName, arg.Name, arg.OrganizationID)
	var i GetBucketByNameRow
	err := row.Scan()
	return i, err
}
