// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: minio_credentials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMinioCredential = `-- name: CreateMinioCredential :one
INSERT INTO minio_credentials (organization_id, name, access_key, secret_key_hash, policy)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, name, access_key, secret_key_hash, policy, created_at, updated_at
`

type CreateMinioCredentialParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	Name           string      `json:"name"`
	AccessKey      string      `json:"access_key"`
	SecretKeyHash  string      `json:"secret_key_hash"`
	Policy         []byte      `json:"policy"`
}

func (q *Queries) CreateMinioCredential(ctx context.Context, arg CreateMinioCredentialParams) (MinioCredential, error) {
	row := q.db.QueryRow(ctx, createMinioCredential,
		arg.OrganizationID,
		arg.Name,
		arg.AccessKey,
		arg.SecretKeyHash,
		arg.Policy,
	)
	var i MinioCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AccessKey,
		&i.SecretKeyHash,
		&i.Policy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMinioCredential = `-- name: DeleteMinioCredential :exec
DELETE FROM minio_credentials WHERE id = $1
`

func (q *Queries) DeleteMinioCredential(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMinioCredential, id)
	return err
}

const getMinioCredentialByAccessKey = `-- name: GetMinioCredentialByAccessKey :one
SELECT id, organization_id, name, access_key, secret_key_hash, policy, created_at, updated_at FROM minio_credentials WHERE access_key = $1
`

func (q *Queries) GetMinioCredentialByAccessKey(ctx context.Context, accessKey string) (MinioCredential, error) {
	row := q.db.QueryRow(ctx, getMinioCredentialByAccessKey, accessKey)
	var i MinioCredential
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.AccessKey,
		&i.SecretKeyHash,
		&i.Policy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrganizationMinioCredentials = `-- name: GetOrganizationMinioCredentials :many
SELECT id, organization_id, name, access_key, secret_key_hash, policy, created_at, updated_at FROM minio_credentials WHERE organization_id = $1
`

func (q *Queries) GetOrganizationMinioCredentials(ctx context.Context, organizationID pgtype.UUID) ([]MinioCredential, error) {
	rows, err := q.db.Query(ctx, getOrganizationMinioCredentials, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MinioCredential
	for rows.Next() {
		var i MinioCredential
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.AccessKey,
			&i.SecretKeyHash,
			&i.Policy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
