// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID             pgtype.UUID        `json:"id"`
	Name           string             `json:"name"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	KeyHash        string             `json:"key_hash"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Organization struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationUser struct {
	ID             pgtype.UUID        `json:"id"`
	OrganizationID pgtype.UUID        `json:"organization_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
