// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOrganizationUserExists = `-- name: CheckOrganizationUserExists :one
SELECT EXISTS (
    SELECT 1 FROM organization_users 
    WHERE organization_id = $1 AND user_id = $2
)
`

type CheckOrganizationUserExistsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckOrganizationUserExists(ctx context.Context, arg CheckOrganizationUserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrganizationUserExists, arg.OrganizationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
