// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: organization_users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkOrganizationUserExists = `-- name: CheckOrganizationUserExists :one
SELECT EXISTS (
    SELECT 1 FROM organization_users 
    WHERE organization_id = $1 AND user_id = $2
)
`

type CheckOrganizationUserExistsParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) CheckOrganizationUserExists(ctx context.Context, arg CheckOrganizationUserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkOrganizationUserExists, arg.OrganizationID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getOrganizationUser = `-- name: GetOrganizationUser :one
SELECT id, organization_id, user_id, created_at FROM organization_users WHERE organization_id = $1 AND user_id = $2 LIMIT 1
`

type GetOrganizationUserParams struct {
	OrganizationID pgtype.UUID `json:"organization_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetOrganizationUser(ctx context.Context, arg GetOrganizationUserParams) (OrganizationUser, error) {
	row := q.db.QueryRow(ctx, getOrganizationUser, arg.OrganizationID, arg.UserID)
	var i OrganizationUser
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}
