// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckOrganizationUserExists(ctx context.Context, arg CheckOrganizationUserExistsParams) (bool, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateOrganizationUser(ctx context.Context, arg CreateOrganizationUserParams) (OrganizationUser, error)
	CreateS3Bucket(ctx context.Context, arg CreateS3BucketParams) (S3Bucket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteS3BucketById(ctx context.Context, id pgtype.UUID) (S3Bucket, error)
	DeleteS3BucketByName(ctx context.Context, arg DeleteS3BucketByNameParams) (S3Bucket, error)
	GetApiKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetBucketByName(ctx context.Context, arg GetBucketByNameParams) (GetBucketByNameRow, error)
	GetOrgFromApiKey(ctx context.Context, keyHash string) (Organization, error)
	GetOrganizationApiKeys(ctx context.Context, organizationID pgtype.UUID) (ApiKey, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationUser(ctx context.Context, arg GetOrganizationUserParams) (OrganizationUser, error)
	GetOrganizationsFromUserId(ctx context.Context, userID pgtype.UUID) ([]Organization, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailPassword(ctx context.Context, arg GetUserByEmailPasswordParams) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	ListApiKeys(ctx context.Context, limit int32) ([]ApiKey, error)
}

var _ Querier = (*Queries)(nil)
