// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckOrganizationUserExists(ctx context.Context, arg CheckOrganizationUserExistsParams) (bool, error)
	CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error)
	CreateOrganization(ctx context.Context, name string) (Organization, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetApiKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error)
	GetOrgFromApiKey(ctx context.Context, keyHash string) (Organization, error)
	GetOrganizationByID(ctx context.Context, id pgtype.UUID) (Organization, error)
	GetOrganizationFromApiKey(ctx context.Context, keyHash string) (Organization, error)
	GetOrganizationUser(ctx context.Context, arg GetOrganizationUserParams) (OrganizationUser, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByEmailPassword(ctx context.Context, arg GetUserByEmailPasswordParams) (User, error)
	GetUserById(ctx context.Context, id pgtype.UUID) (User, error)
	ListApiKeys(ctx context.Context, limit int32) ([]ApiKey, error)
}

var _ Querier = (*Queries)(nil)
